name: cheeseball
description: Cheeseball - Buy, Sell & Swap Crypto
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.0
  google_fonts: ^6.1.0
  flutter_paystack_plus: ^2.0.2
  http: ^1.2.0
  qr_flutter: ^4.1.0
  lucide_icons: ^0.257.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  url_launcher: ^6.2.0
  provider: ^6.1.0
  go_router: ^14.0.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
